name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20    # 不用 cache: npm（你没有锁文件）

      - name: Show project summary
        run: |
          set -x
          node -v
          npm -v
          ls -la
          test -f package.json && cat package.json
          test -f next.config.js && cat next.config.js

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build & Export
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1
          NEXT_DISABLE_ESLINT: 1        # 跳过 ESLint（避免构建因 lint 失败）
          TSC_COMPILE_ON_ERROR: true    # 有 TS 报错也继续产物（先上线）
        run: |
          npx next telemetry disable || true
          npm run build --silent
          npm run export --silent
          echo "OUT CONTENTS:"
          ls -la out || true

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
